### ISSUE TITLE
Issues converting d-specs to free form

### ISSUE THREAD

**Issue by a4ginatl** [BrianGarland/vscode-rpgfree#51] opened 2022-11-11 19:08 UTC
Converting Procedure Interfaces (PI), it is not converting correctly.
    Dcl-PI jrn_fix_02  extpgm('JRN_FIX_02');
      Lib_to_Check   Char(10a);
      New_Jrn        Char(10a);
      New_Jrn_Lib    Char(10a);
    End-PI;
It correctly changes to CHAR() but the a should be removed.
Old Code:
d wfield 10a
The other issue I found is it randomly adds End-PR:

**Comment by BrianGarland** [comment] 2022-11-17 13:40
@a4ginatl I cannot reproduce this.   
Which version of RPGLE Free are you using?  
Please provide the before source so I can try exactly what you have.

**Comment by a4ginatl** [comment] 2022-11-17 16:28
We are on v7.3.

 

I cleaned up the program and do not have an example right now.

 

I’ll try to find an existing program that I can show you the issue. That will be in a few days. I have some deadlines to meet.

 

Thank you.

Darryl Freinkel

A4G

Telephone: 770.321.8562 Mobile: 678.355.8562

**Comment by BrianGarland** [comment] 2023-02-15 19:27
Not hearing anything I'm going to close this issue.  

Please make sure you are on the latest version of VS Code and the extensions. 

If you can reproduce it while using the latest please open a new issue with the sample code before and after the conversion.

**Closed by BrianGarland** 2023-02-15 19:27 UTC

**Comment by a4ginatl** [comment] 2023-02-15 21:43
Please close.

 

Thanks

 

Darryl Freinkel

A4G

Telephone: 770.321.8562 Mobile: 678.355.8562
